@baseUrl = http://localhost:5205

GET {{baseUrl}}/api/veiculos
Accept: application/json

###

GET {{baseUrl}}/api/consultas/alugueis-detalhados
Accept: application/json

###

GET {{baseUrl}}/api/consultas/faturamento-por-categoria
Accept: application/json
